---

- name: 3-tier-app config
  hosts: all
  gather_facts: false
  become: true
  roles:
    - { name: baseline, tags: baseline }


  tasks:
  - name:  loadbalancer installation
    hosts: frontends
    gather_facts: false
    become: yes
    roles:
     - {name: lb, tags: lb}
